version: '3.11'

services:
  backend:
    build: .
    container_name: 'DjangoTodoApp-container'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
